name: Upload Artifact

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - artifacts

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: |
          date -Isec >artifact_test.txt
          echo "Run ID: $GITHUB_RUN_ID" >> artifact_test.txt
          echo "Run Number: $GITHUB_RUN_NUMBER" >> artifact_test.txt
          echo "Commit SHA: $GITHUB_SHA" >> artifact_test.txt
          echo "Branch/Ref: $GITHUB_REF" >> artifact_test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: artifact-test
          path: artifact_test.txt
