name: Testing GH API

on:
  workflow_dispatch:
  push:

jobs:
  with-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh run list

  without-repo:
    runs-on: ubuntu-latest
    steps:
      - run: gh run list --repo ${{ github.repository }}
