name: Test getting secrets based on conditions

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - secrets-if

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    env:
      SECRET_CUSTOMER: customer1
    steps:
      - name: Get Secrets 1
        env:
          SECRET_ENV: ea
          SECRET_CUSTOMER: customer1
        run: |
          echo "Secret for ${SECRET_CUSTOMER} = " ${{ vars[env.SECRET_CUSTOMER] }}
      - name: Get Secrets 2
        env:
          SECRET_ENV: ea
          SECRET_CUSTOMER: customer2
        run: |
          echo "Secret for ${SECRET_CUSTOMER} = " ${{ vars[env.SECRET_CUSTOMER] }}
