name: Test getting secrets based on conditions

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      customer:
        description: 'Customer name'
        required: true
      env:
        description: 'Environment'
        required: true
  push:
    branches:
      - secrets-if

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        run: |
          echo "Customer: ${{ github.event.inputs.customer }}"
          echo "Environment: ${{ github.event.inputs.env }}"

          customer_secret="${{ vars[github.event.inputs.customer] }}"
          customer_env_secret="${{ vars[format('{0}_{1}', github.event.inputs.customer, github.event.inputs.env)] }}"

          if [ -n "$customer_env_secret" ]; then
            echo "Using customer and environment specific secret."
            echo "Secret: $customer_env_secret"
          elif [ -n "$customer_secret" ]; then
            echo "Using customer specific secret."
            echo "Secret: $customer_secret"
          else
            echo "No matching secret found."
          fi
