name: Test getting secrets based on conditions

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - secrets-if

env:
  SECRET_ENV: ea
  SECRET_CUSTOMER: customer1

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets 1
        run: |
          echo "Secret for ${SECRET_CUSTOMER} = " ${{ vars[env.SECRET_CUSTOMER] }}
          echo "Secret for ${SECRET_CUSTOMER} ${SECRET_ENV} = " ${{ vars[format('{0}_{1}', env.SECRET_CUSTOMER, env.SECRET_ENV)] }}
  get-secrets-2:
    runs-on: ubuntu-latest
    env:
      SECRET_CUSTOMER: customer2
    steps:
      - name: Get Secrets 2
        run: |
          echo "Secret for ${SECRET_CUSTOMER} = " ${{ vars[env.SECRET_CUSTOMER] }}
          echo "Secret for ${SECRET_CUSTOMER} ${SECRET_ENV} = " ${{ vars[format('{0}_{1}', env.SECRET_CUSTOMER, env.SECRET_ENV)] }}
