name: Rollback testing
on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          echo "Setup"
          exit 1

  deploy-be:
    runs-on: ubuntu-latest
    needs: [ "setup" ]
    steps:
      - name: Step 1
        run: echo "Step 1"
      - name: Step 2
        run: |
          echo "Step 2"
          exit 0
      - name: Step 3
        run: echo "Step 3"

  deploy-fe:
    runs-on: ubuntu-latest
    needs: [ "setup" ]
    steps:
      - name: Step 1
        run: echo "Step 1"
      - name: Step 2
        run: |
          echo "Step 2"
          exit 0
      - name: Step 3
        run: echo "Step 3"

  restart:
    runs-on: ubuntu-latest
    needs: [ "deploy-be", "deploy-fe" ]
    steps:
      - name: Restart
        run: |
          echo "Restarted"
          exit 0

  statuses:
    runs-on: ubuntu-latest
    needs: [ "setup", "deploy-be", "deploy-fe", "restart" ]
    steps:
      - run: |
          echo "Setup: ${{ needs.setup.result }}"
          echo "Deploy BE: ${{ needs.deploy-be.result }}"
          echo "Deploy FE: ${{ needs.deploy-fe.result }}"
          echo "Restart: ${{ needs.restart.result }}"

  rollback:
    runs-on: ubuntu-latest
    needs: [ "deploy-be", "deploy-fe", "restart" ]
    if: failure() && ( needs.deploy-be.result == 'failure' || needs.deploy-fe.result == 'failure' || needs.restart.result == 'failure' )
    steps:
      - name: Rollback
        run: echo "Rollback"
