name: Testing dynamically set env vars

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      random_output: ${{ steps.set.outputs.random_output }}
    steps:
      - name: Set env var
        id: set
        run: |
          random_number=$(($RANDOM % 10))
          echo "random_output=$random_number" >> $GITHUB_OUTPUT
          echo "random_env=$random_number" >> $GITHUB_ENV
          echo "::notice::Random number: $random_number"
      - name: Use env var in same job
        run: |
          echo "random_output=${{ steps.set.outputs.random_output }}"
          echo "random_env=$random_env"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Use env var in another job
        needs: [ job1 ]
        run: |
          echo "random_output=${{ needs.job1.outputs.random_output }}"
          echo "random_env=$random_env"
